# Generated by Django 5.1.7 on 2025-10-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('images', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'emotion_analyzer',
                'default_permissions': (),
            },
        ),
    ]
